#!/usr/bin/env bash
# Buzz

i=1

while [ "$i" -lt 101 ]; do 
    if ! (( i%3 )) && ! (( i%5 )); then
        echo "FizzBuzz"
    elif ! (( i%3 )); then
        echo "Fizz"
    elif ! (( i%5 )); then
        echo "Buzz"
    else
        echo "$i"
    fi                
    ((i++))
done
