#!/usr/bin/env bash
# Badluck is not my portion, this code must run
i=1

while [ "$i" -lt 11 ]; do
    
    if [[ $i -eq 4 ]]; then
        echo "bad luck"
    elif [[ $i -eq 8 ]]; then
        echo "good luck"
    else 
        echo "Best School"
    fi 
    ((i++))          
done
