#!/usr/bin/env bash
# create file in /var/run/myscript.pid containing its pid
# print into the file and deletes it and terminates itself

echo $$ >> /var/run/myscript.pid;
trap '
    echo  "I hate the kill command"
    rm -rf /var/run/myscript.pid
    exit' 15

trap '
    echo "Y U no love me?!" ' 2

trap 'rm -rf /var/run/myscrip.pid' 3
while true 
do
    echo "TO infinity and beyond"
    sleep 2
done
