#!/usr/bin/env bash
# script to manage deamon

PROGRAM='manage_my_process'
RELPATH="${0%/*}/${PROGRAM}"
PIDFILE="${PIDFILE:-/var/run/my_process.pid}"
declare -A MESSAGES=( 
  ['start']='started'
  ['stop']='stopped'
  ['restart']='restarted'
)

start() {
  exec -- "${RELPATH}" &
  echo "$!" >| "${PIDFILE}"
}

stop() {
  trap '
    trap RETURN
    rm -f -- "${PIDFILE}"
  ' RETURN
  kill -- "$(< "${PIDFILE}")" 2> /dev/null
}

restart() {
  stop
  start
}

if (( $# == 1 )) && [[ -v "MESSAGES[$1]" ]]
then
  "$1" && printf '%s %s\n' "${PROGRAM}" "${MESSAGES[$1]}"
else
  printf 'Usage: %s {start|stop|restart}\n' "${PROGRAM}"
  exit 1
fi
